export const ASYNC_IS_LOGGED = "ASYNC_IS_LOGGED";
export const ASYNC_CATEGORIES = "ASYNC_CATEGORIES";
export const ASYNC_WALLETS = "ASYNC_WALLETS";
export const ASYNC_FINANCES = "ASYNC_FINANCES";
export const ASYNC_BUDGETS = "ASYNC_BUDGETS";